const data = {
    products: [
        {
            _id: '1',
            name: 'Oxy T-Shirt',
            category: 'Shirt',
            image:'/images/p1.jpg',
            price: 30,
            countInStock: 10, 
            brand: 'NIKE',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id: '2',
            name: 'Oxy ClassNameic T-Shirt',
            category: 'Shirt',
            image:'/images/p3.jpg',
            price: 30,
            countInStock: 20, 
            brand: 'NIKE',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },        {
            _id: '3',
            name: 'Oxy T-Shirt',
            category: 'Shirt',
            image:'/images/p1.jpg',
            price: 20,
            countInStock: 65,
            brand: 'NIKE',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },        {
            _id: '4',
            name: 'Oxy Tote Bag',
            category: 'Shirt',
            image:'/images/p4.jpg',
            price: 20,
            countInStock: 30,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },        {
            _id: '5',
            name: 'Oxy T-Shirt',
            category: 'Shirt',
            image:'/images/p2.jpg',
            price: 50,
            countInStock: 0,
            brand: 'NIKE',
            rating: 3.5,
            numReviews: 10,
            description:'high quality product',
        },        {
            _id: '6',
            name: 'Oxy Hoody',
            category: 'Shirt',
            image:'/images/p2.jpg',
            price: 100,
            countInStock: 15, 
            brand: 'Champion',
            rating: 4.0,
            numReviews: 10,
            description:'high quality product',
        },
    ]
}
export default data; 